# Dockerfile

FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

# Copia o JAR gerado pelo Maven (você precisa compilar antes com mvn package)
COPY target/avaliacao-0.0.1-SNAPSHOT.jar /app/avaliacao.jar

EXPOSE 8083

CMD ["java", "-jar", "/app/avaliacao.jar"]